language: cpp

os:
    - linux
    - windows

services:
    - docker
  
addons:
    apt:
        packages:
            - docker-ce

env:
    jobs:
        - SMBRANCH=1.8-dev
        - SMBRANCH=1.9-dev
        - SMBRANCH=1.10-dev
        - SMBRANCH=master
    global:
        - CACHE_DIR=build-$TRAVIS_OS_NAME
        
before_script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build -t system2 . ; fi
    - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install -y visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64" ; fi

script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run -w /build --env SMBRANCH=$SMBRANCH -v $(pwd):/build system2 bash build.sh ; fi
    - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then ./build.bat ; fi

#cache:
#    directories:
#        - $CACHE_DIR
    
deploy:
    - provider: releases
      skip_cleanup: true
      api_key:
          secure: sgqauwMNqwXWsv4TGrfaq2DdttS4bYLSa7xQrMaPUFpvecgfGS7ObmoRxgb9qrjTNISNkV8JZre+TmPkTaCdkIww5waS5efUBs4EJYeqlG55gxLx5UgC6S3w8EKsJKdnaLrLqr8mzbb2e3+vzI8v2f/mkd0HqQnu/zMdnBV5ZTS1Bey5WNkqMTl9vxZ1lksZKqeR5X0oatkjlRe+BHTBzNq9DnkOHbgV02QlTI4OSrOwfwqWeHMeAVbbcZiN0JCHoWqA/ES/+SZWsZ3T5VhfvQOm8C0rzeRk/PSixNA34GSE54tSkstQ5KAO/eyg1faVE8dh0szHLEl3sLaRERtGZAirYtghTTTcAf2OEM3890PKbkOfT36hoTKBbIr1Kak++SXz+OI3YhLMe0Mhl5h/JtevZRM4mvub4LTxMFseJTIQTl0a7XHyubl0NAyTrH/Lhnx/V82HiygiVS/l0+/iZcmjTH4RWkmGgKM5RkhXnq5iy56a7jbTu3UDqkh7WUQd50IdemxHOpm7W5fejJ98vJomfEGalEXS78IzzQ4RhQEiMSTYonfrRHCr6qWoiTkAp4i7Wew5bOV75XQzDdMhNfQmQgrwsK92lwM6cB5tCtP5yoq/aig+y/MtDCYiyoM+qJpfcVEJEIE1FPW42f5ePcmBwE78Hs6xBJ11bOfBBKI=
      file:
          - Release/system2.ext.so
          - msvc19/Release/system2.ext.dll
          - sourcemod/data/system2/ca-bundle.crt
      on:
          condition: "$SMBRANCH = 1.10-dev"
          repo: dordnung/System2
          all_branches: true
          tags: true